spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: false

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
      last-name: User
    database:
      type: h2
      schema-update: true
    history-level: audit
    authorization:
      enabled: false
    generic-properties:
      properties:
        history-time-to-live: "P1D"
logging:
  level:
    org.camunda.bpm.engine: INFO
    com.example.workflow: INFO

management:
  endpoints:
    enabled-by-default: false